services:
  # Servidor Web
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:default.conf
    depends_on:
      - php

  # Aplicaci√≥n Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

volumes:
  mysql_data:
